spring:
  application:
    name: coflo

  profiles:
    active: local
    include: oauth

  output:
    ansi:
      enabled: always

openai:
  api:
    key: ${OPENAI_API_KEY}
    organization: ${OPENAI_ORGANIZATION}
    project: ${OPENAI_PROJECT}

crypto-key: ${CRYPTO_KEY}
