spring:
  application:
    name: coflo

  profiles:
    active: ${DEV_ACTIVE_PROFILE}
    include: jwt, oauth2

  output:
    ansi:
      enabled: always

gitlab:
  api:
    project-list: /api/v4/projects
    user-info: /api/v4/user

crypto-key: ${CRYPTO_KEY}