spring:
  application:
    name: coflo

  profiles:
    active: local
    include: oauth

  output:
    ansi:
      enabled: always

openai:
  api:
    key: ${OPENAI_API_KEY}

crypto-key: ${CRYPTO_KEY}
