spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coflo
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

redirect-regist-url: ${REDIRECT_REGIST_URL}
redirect-main-url: ${REDIRECT_MAIN_URL}
